demo:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: mysql7.sqlpub.com
    port: 3312
    database: z7q3pova87a
    username: o0m2cr
    password: xDoFwVJXGyHWuBuw
  jwt:
    # jwt签名加密时使用的密钥
    secret-key: awsl
    # jwt过期时间 2小时 (=2 * 60 * 60 * 1000)
    ttl: 7200000
  front:
    ip:
      - http://localhost:3000
      - http://localhost:5173
  exclude:
    path:
      - /user/login
      - /user/register
      - /user/info
      - /news/**
      - /home/**
      - /book/category
      - /book/all
      - /book/info/{id}
      - /book/chapter
      - /book/random
      - /book/rank
      - /book/content
      - /book/search
      - /book/state
      - /captcha
      - /comment/top
      - /comment/child
